### ISSUE TITLE
Remove SQLite Enums

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma-engines#557] opened 2020-03-05 13:09 UTC
Currently only Mysql and Postgres make use of native enums. Sqlite still uses strings since it does not have native enum support. 

We should update the parser/validator to disallow enums for Sqlite the parser. 
This will then also necessitate some changes to our testing suite.

**Comment by mavilein** [comment] 2020-04-14 13:15
closing as duplicate of: https://github.com/prisma/migrate/issues/377

**Closed by mavilein** 2020-04-14 13:15 UTC
Labels: team/engines
