### ISSUE TITLE
Bug: subquery has too many columns

### ISSUE THREAD

**Issue by tvvignesh** [prisma/prisma-engines#646] opened 2020-04-02 09:24 UTC
I used to run a query which used to work during preview but doesn't now. Not sure if I am doing anything wrong. It says:

```
Caught Error:: PrismaClientUnknownRequestError:
Invalid `userList = await db.userAuthentication.findMany()` invocation in
/app/server/src/app/utils/core/auth.utils.ts:554:52
   550         }
   551     };
   552 }
   553 
→  554 let userList = await db.userAuthentication.findMany(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42601"), message: "subquery has too many columns", detail: None, hint: None, position: Some(Original(284)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_expr.c"), line: Some(2070), routine: Some("transformSubLink") }) }) })
    at PrismaClientFetcher.request (/app/server/dist/generated/prisma/runtime/index.js:1:51485)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

when I run
```
let userList = await db.userAuthentication.findMany({
            where: { emails: { some: { value: 'xyz@example.com' } } },
            first: 1,
            select: {
                id: true,
                local: true,
                username: true,
                emails: true,
                mobiles: true,
                status: true,
                password: true
            }
        });
```

The generated SQL query is this:
```sql
SELECT "public"."UserAuthentication"."id", "public"."UserAuthentication"."local", "public"."UserAuthentication"."username", "public"."UserAuthentication"."status", "public"."UserAuthentication"."password" FROM "public"."UserAuthentication" WHERE ("public"."UserAuthentication"."id") IN (SELECT "t0".* FROM "public"."EmailSchema" AS "t0" INNER JOIN "public"."EmailSchema" AS "j0" ON ("j0"."id") = ("t0"."id") WHERE "j0"."value" = $1) ORDER BY "public"."UserAuthentication"."id" ASC LIMIT $2 OFFSET $3
```

Even if I change the query to use include instead of select, I get the same issue:

```
let userList = await db.userAuthentication.findMany({
            where: { emails: { some: { value: 'xyz@example.com' } } },
            first: 1,
            include: {
                emails: true,
                mobiles: true
            }
        });
```

gives:

```
Caught Error:: PrismaClientUnknownRequestError: 
Invalid `userList = await db.userAuthentication.findMany()` invocation in
/app/server/src/app/utils/core/auth.utils.ts:570:52

   566 //         password: true
   567 //     }
   568 // });
   569 
→  570 let userList = await db.userAuthentication.findMany(

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42601"), message: "subquery has too many columns", detail: None, hint: None, position: Some(Original(746)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_expr.c"), line: Some(2070), routine: Some("transformSubLink") }) }) })
    at PrismaClientFetcher.request (/app/server/dist/generated/prisma/runtime/index.js:1:51485)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

and the query is:

```sql
SELECT "public"."UserAuthentication"."id", "public"."UserAuthentication"."local", "public"."UserAuthentication"."username", "public"."UserAuthentication"."password", "public"."UserAuthentication"."facebook", "public"."UserAuthentication"."google", "public"."UserAuthentication"."github", "public"."UserAuthentication"."microsoft", "public"."UserAuthentication"."linkedIn", "public"."UserAuthentication"."gitlab", "public"."UserAuthentication"."amazon", "public"."UserAuthentication"."pushToken", "public"."UserAuthentication"."status", "public"."UserAuthentication"."metadata", "public"."UserAuthentication"."createdDate", "public"."UserAuthentication"."updatedDate" FROM "public"."UserAuthentication" WHERE ("public"."UserAuthentication"."id") IN (SELECT "t0".* FROM "public"."EmailSchema" AS "t0" INNER JOIN "public"."EmailSchema" AS "j0" ON ("j0"."id") = ("t0"."id") WHERE "j0"."value" = $1) ORDER BY "public"."UserAuthentication"."id" ASC LIMIT $2 OFFSET $3
```

**PS: It worked well during preview**

**Comment by pimeys** [comment] 2020-04-02 09:37
Let's put a prettified SQL

```sql
SELECT
    "public"."UserAuthentication"."id",
    "public"."UserAuthentication"."local",
    "public"."UserAuthentication"."username",
    "public"."UserAuthentication"."status",
    "public"."UserAuthentication"."password"
FROM "public"."UserAuthentication" WHERE ("public"."UserAuthentication"."id") IN (
    SELECT "t0".* FROM "public"."EmailSchema" AS "t0"
    INNER JOIN "public"."EmailSchema" AS "j0" ON ("j0"."id") = ("t0"."id")
    WHERE "j0"."value" = $1
)
ORDER BY "public"."UserAuthentication"."id" ASC
LIMIT $2 OFFSET $3
```

We see a join with one column on the left and `SELECT *` on the right, which obviously doesn't work. Seems like a regression to me.

**Comment by pimeys** [comment] 2020-04-02 10:12
In the end this was a faulty datamodel that didn't follow our new relation guidelines. What is a bug in here is that our validator should point out this error and not let the query engine to start.

**Comment by pimeys** [comment] 2020-04-02 10:15
The faulty relation line looks something like this:
``` prisma
  userAuthentication UserAuthentication? @relation(references: [id])
```
As we see we miss the fields definition.

**Comment by mavilein** [comment] 2020-04-06 14:53
This is a duplicate of: https://github.com/prisma/prisma/issues/2064
We are close to having a fix ready.

**Closed by mavilein** 2020-04-06 14:53 UTC
Labels: component: data model parser, kind/regression
