### ISSUE TITLE
[DA] Planetscale engine tests: one2m_mix_required_writable_readable

### ISSUE THREAD

**Issue by miguelff** [prisma/prisma-engines#4482] opened 2023-11-21 12:53 UTC
This is a subcluster of failures after having enabled planetscale tests in https://github.com/prisma/prisma-engines/pull/4423
 
 
Failing tests in this cluster:

```
writes::relations::compound_fks_mixed_requiredness::compound_fks::one2m_mix_required_writable_readable
```

Please follow [this process](https://prismaio.notion.site/Process-for-tackling-Planetscale-failing-tests-75e280e923e64e2aadf9e367a42aef8b)

**Comment by jkomyno** [comment] 2024-06-06 09:26
I can confirm that this still fails on both Napi and Wasm, with

```
Expected result to return an error, but found success: {"data":{"createOnePost":{"id":2,"user_id":2,"user_age":2,"User":null}}}
```

The reason is that, on PlanetScale, we don't have foreign key violations. We should thus get rid of

```rust
  // Foreign key violation
  assert_error!(
      &runner,
      r#"mutation{createOnePost(data:{id: 2, user_id:2, user_age: 2}){id, user_id, user_age, User{id}}}"#,
      2003
  );
```

for PlanetScale only.

**Comment by jkomyno** [comment] 2024-06-07 12:47
Fixed via https://github.com/prisma/prisma-engines/pull/4909

**Closed by jkomyno** 2024-06-07 12:47 UTC
Labels: topic: driver adapters
